Hw02 express
artemhoriuk1994/nodejs-express-hw pull request #1
Opened 2022-11-03 12:23 UTC by artemhoriuk1994

Fixed function updateContact. Remove status and code from the returned object

2022-11-04 19:37 UTC, Eastvarga commented on models/contacts.js
> +  const reassignedContact = Object.assign(findedContact, {
не корректна логіка якщо невірний айді в запиті - повертає помилку {
    "message": "Cannot convert undefined or null to object"
}
додайте обробку якщо елемент з айді у запиті не знайдено в списку

2022-11-04 19:38 UTC, Eastvarga commented on routes/api/contacts.js
> +const scheme = Joi.object({
валідацію краще винести в окремий модуль

2022-11-04 19:42 UTC, Eastvarga commented on routes/api/contacts.js
> +      contacts
json(contacts) достатньо, зайва вкладеність тут не потрібна.
Ви повинні розуміти що в відповіді отримаєте поле з ім'ям змінної котру вклали у дужки {} у джойні

2022-11-04 19:46 UTC, Eastvarga requested changes
Є зауваження до коду, треба їх усунути

2022-11-04 21:52 UTC, artemhoriuk1994 commented on models/contacts.js
> +  const reassignedContact = Object.assign(findedContact, {
додав перевірку контакту і помилку якщо його немає

2022-11-04 21:52 UTC, artemhoriuk1994 commented on routes/api/contacts.js
> +const scheme = Joi.object({
виніс в окремий файл

2022-11-04 21:53 UTC, artemhoriuk1994 commented on routes/api/contacts.js
> +      contacts
прибрав зайву вкладеність 
тепер повертає чистий json без підписів

2022-11-05 08:47 UTC, Eastvarga approved these changes

2022-11-05 08:47 UTC, merged