Home work 05
artemhoriuk1994/nodejs-express-hw pull request #6
Opened 2022-11-24 01:29 UTC by artemhoriuk1994

Create function to adding image

2022-11-24 19:09 UTC, Eastvarga commented on .gitignore
> +tmp
Отже, як вважаєте без теки tmp чи буде Ваш код працювати?

2022-11-24 19:16 UTC, Eastvarga commented on src/controler/users.controler.js
> +  const avatarURL = path.join("avatars", _id + originalname);
http://localhost:3000/avatars/636f61c8a188a0a8bdea1b51my%20photo%20mini.jpg
 Ваш URL повинен мати подібний вигляд, зараз це не так

2022-11-24 19:18 UTC, Eastvarga commented on src/middlewares/storageMiddleware.js
> +const tmpDir = path.join(process.cwd(), "tmp")
цієї папки не існує. Спроба записати файл у цю папку не буде вдала!

2022-11-24 19:18 UTC, Eastvarga commented on src/routes/api/authRoute.js
> +authRouter.patch("/", validationSchema(schemePatchSub), auth, tryCatchWrapper(setSubcription));
завжди перша йде авторізація - не авторизований запит навіть валідувати не треба!!

2022-11-24 19:19 UTC, Eastvarga requested changes
Є зауваження

2022-11-25 18:54 UTC, artemhoriuk1994 commented on .gitignore
> +tmp
повернув папку tmp

2022-11-25 18:56 UTC, artemhoriuk1994 commented on src/controler/users.controler.js
> +  const avatarURL = path.join("avatars", _id + originalname);
avatars\637ec3b5cfdad0748504010fjpegsystems-home.jpg

в данний момент шлях виглядає так 
і при переході по: 
http://localhost:3000/avatars/637ec3b5cfdad0748504010fjpegsystems-home.jpg
повертає картинку

2022-11-25 18:57 UTC, artemhoriuk1994 commented on src/middlewares/storageMiddleware.js
> +const tmpDir = path.join(process.cwd(), "tmp")
папку повернув

2022-11-25 23:02 UTC, Eastvarga commented on src/controler/users.controler.js
> +  const avatarURL = path.join("avatars", _id + originalname);
Тоді скажіть що з цього є URL
avatars\637ec3b5cfdad0748504010fjpegsystems-home.jpg
чи
http://localhost:3000/avatars/637ec3b5cfdad0748504010fjpegsystems-home.jpg
?

2022-11-27 19:04 UTC, artemhoriuk1994 commented on src/controler/users.controler.js
> +  const avatarURL = path.join("avatars", _id + originalname);
Виправив дану помилку

2022-11-28 15:37 UTC, Eastvarga approved these changes

2022-11-28 15:37 UTC, merged